version: "3"

volumes:
  produtosdata:

networks:
  frontend:
  backend:

services:
  mysql:
    image: "mysql:8.0.27"
    environment:
      - MYSQL_ROOT_PASSWORD=numsey
      - bind-adress=0.0.0.0
    volumes:
      - produtosdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    networks:
      - backend
  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DHOST=mysql
    networks:
      - backend
      - frontend
    ports:
      - 5000:8000
    depends_on:
      - mysql